title: "Darshana Lakmal Weerawarne"
url: ""
baseurl: "/"

markdown: kramdown

tracking_id: #

footer: no

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "about"  
 - name: "Publications"
   link: "publications"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
