title: "Darshana Lakmal Weerawarne"
url: "https://dlweerawarne.github.io"
baseurl: ""

markdown: kramdown

tracking_id: #

footer: no

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: ""  
 - name: "Publications"
   link: "publications"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
