title: ""
description: "Darshana L Weerawarne"
keywords: "darshana, lakmal, weerawarne, Sri Lanka, Binghamton, colombo, univeristy, uoc, physics, electronics, flexible, SUNY"
url: "https://dlweerawarne.github.io"
baseurl: "/"

markdown: kramdown

tracking_id: #

plugins_dir:
  - jekyll-seo-tag

footer: no

sass:
    style: compressed
    sass_dir: _sass

# Author settings
author:
  name     : "Darshana L Weerawarne"
  job      : "Senior Lecturer @ University of Colombo"
  greeting : ""
  bio      : ""
  thumb    : #/assets/images/sherlock.jpg
  email    : #hnrird@gmail.com
  url      : #http://heiswayi.github.io
  github   : #http://github.com/heiswayi
  twitter  : #http://twitter.com/HeiswayiNrird
  facebook : #https://www.facebook.com/heiswayi.nrird
  linkedin : https://lk.linkedin.com/in/dlweerawarne

nav:
 - name: "About"
   link: "/"  
 - name: "Publications"
   link: "publications"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Resources"
   link: "resources"
 - name: "Contact"
   link: "contact"
